# Use the latest LTS version of Node.js
FROM node:18-alpine
 
# Set the working directory inside the container
WORKDIR /app
 
# Copy package.json and package-lock.json
COPY package*.json ./
 
# Install dependencies
RUN npm install
 
# Copy the rest of your application files
COPY . .
 
# Expose the port your app runs on
EXPOSE 4173

# for local below line not required
RUN npm run build   
 
# Define the command to run your local app
#CMD ["npm", "start"]

# Define the command to run your prod app
CMD ["npm", "run", "build"]